### ISSUE TITLE
Add to Github's Linguist.

### ISSUE THREAD

**Issue by mthadley** [bendman/language-soy#16]
Hey @bendman, thanks for creating this project!

I wanted to ask you about adding your syntax grammar to [`linguist`](https://github.com/github/linguist), which would enable syntax highlighting and language detection for soy templates on Github. Is this something you would be interested in adding?

I am completely free to work on this myself, and I think I can actually do most of it (at least the work on the `linguist` side). However I wanted to check with you, the owner, first. Is this a project that you still willing/able to maintain? I'm sure there will be more issues that show up (I found a few myself with the highlighting that I will report soon, and maybe send PR's), but I wanted to see how you felt. 

Thanks again!

**Comment by mthadley** [comment]
Closing this since I ended up submitting a grammar [here](https://github.com/github/linguist/pull/3634).

**Comment by bendman** [comment]
Hey @mthadley, @ptsurko has been more actively maintaining this lately, as it's been a few years since I've done anything with soy.

An option might be to add a deprecation notice to this repo and link to yours, if that one is more likely to be actively maintained.

**Comment by mthadley** [comment]
@bendman Thanks for getting back to me, I really appreciate it. I sort of figured that might be the case, since that has been my experience with a lot of the community built soy tooling.

It's up to you if you would like to add the notice, but I do plan on maintaining my repo for at least the near future.
